name: Download Chocolatey Packages
on: [workflow_dispatch]  # 手动触发
jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Install Chocolatey
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex (irm https://community.chocolatey.org/install.ps1)
      - name: Download Packages
        run: |
          choco install git -y --no-progress --force --download-only
          choco install notepadplusplus -y --no-progress --force --download-only
      - name: Archive Packages
        run: |
          Compress-Archive -Path "$env:ChocolateyInstall\lib" -DestinationPath packages.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: offline-packages
          path: packages.zip
